// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPDTkOQzBJj88Yixmdkwg1DALoSU7dd48',
    appId: '1:721139914126:web:aa369f32d535b76fc480df',
    messagingSenderId: '721139914126',
    projectId: 'ecowaste-cotonou',
    authDomain: 'ecowaste-cotonou.firebaseapp.com',
    storageBucket: 'ecowaste-cotonou.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0te9zgVAOwG5RAPSGYM0xi-ZCTuEdbRQ',
    appId: '1:721139914126:android:f3b2b1f907e6db48c480df',
    messagingSenderId: '721139914126',
    projectId: 'ecowaste-cotonou',
    storageBucket: 'ecowaste-cotonou.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDytfsgEQjTV3SzFYhmUMabslj1lc4iGSw',
    appId: '1:721139914126:ios:50c03a047fb51c53c480df',
    messagingSenderId: '721139914126',
    projectId: 'ecowaste-cotonou',
    storageBucket: 'ecowaste-cotonou.firebasestorage.app',
    androidClientId: '721139914126-l2flokj35uj8d9vudn65gd92m05usgas.apps.googleusercontent.com',
    iosClientId: '721139914126-aa0llc1mncgn2mftcvnqqneep46b2a1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecowasteCotonou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDytfsgEQjTV3SzFYhmUMabslj1lc4iGSw',
    appId: '1:721139914126:ios:50c03a047fb51c53c480df',
    messagingSenderId: '721139914126',
    projectId: 'ecowaste-cotonou',
    storageBucket: 'ecowaste-cotonou.firebasestorage.app',
    androidClientId: '721139914126-l2flokj35uj8d9vudn65gd92m05usgas.apps.googleusercontent.com',
    iosClientId: '721139914126-aa0llc1mncgn2mftcvnqqneep46b2a1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecowasteCotonou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPDTkOQzBJj88Yixmdkwg1DALoSU7dd48',
    appId: '1:721139914126:web:d2322a2eb0ac2927c480df',
    messagingSenderId: '721139914126',
    projectId: 'ecowaste-cotonou',
    authDomain: 'ecowaste-cotonou.firebaseapp.com',
    storageBucket: 'ecowaste-cotonou.firebasestorage.app',
  );

}